---
- name: Install K3s on all nodes
  hosts: all
  become: true
  vars:
    k3s_token: "{{ lookup('env', 'K3S_TOKEN') }}"
    etcd_url: "https://10.0.0.1:6443"

  tasks:
    - name: Update apt repositories and install curl
      apt:
        update_cache: yes
        name: curl
        state: present

    - name: Install K3s on server nodes
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server --server {{ etcd_url }} --token {{ k3s_token }} --disable-etcd
      when: inventory_hostname in groups['servers']
      register: k3s_install_server
      ignore_errors: yes

    - name: Install K3s on worker nodes
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL={{ etcd_url }} K3S_TOKEN={{ k3s_token }} sh -
      when: inventory_hostname in groups['workers']
      register: k3s_install_worker
      ignore_errors: yes

    - name: Check if K3s installation on server was successful
      debug:
        msg: "K3s installation successful on {{ inventory_hostname }}"
      when: k3s_install_server.rc == 0
      failed_when: k3s_install_server.rc != 0

    - name: Check if K3s installation on worker was successful
      debug:
        msg: "K3s installation successful on {{ inventory_hostname }}"
      when: k3s_install_worker.rc == 0
      failed_when: k3s_install_worker.rc != 0
