components:
  applications:
    - name: traefik
      chart: traefik/traefik
      version: "34.4.1"
      releaseName: traefik 
      repoUrl: "https://traefik.github.io/charts"
      namespace: wave-one
      clusterName: default 
      environment: development
      source:
        chart: traefik
        repoURL: "https://traefik.github.io/charts"
        targetRevision: "34.4.1"
    - name: vault
      chart: hashicorp/vault
      version: "0.24.0"
      releaseName: vault
      repoUrl: "https://helm.releases.hashicorp.com"
      namespace: wave-one
      clusterName: default
      environment: development
      source:
        chart: vault
        repoURL: "https://helm.releases.hashicorp.com"
        targetRevision: "0.24.0"