apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: postgresql
  targetNamespace: argocd
  version: 11.5.0
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/postgres/values.yaml'
