apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: edge  # You can change this if you want a different namespace
spec:
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.26.0-alpha.0  # Specify the version you want
  destination:
    server: https://kubernetes.default.svc
    namespace: edge
  helm:
    valueFiles:
      - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/development/applications/gateway/values.yaml'
      - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/development/applications/gateway/development.yaml'