#cloud-config
packages:
  - git
  - curl
  - vim  # Optional, for troubleshooting
  - ca-certificates

write_files:
  # Define a script that pulls a Git repo and configures K3s
  - path: /etc/init.d/bootstrap_k3s.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      # Pull the repo with Kubernetes manifests
      git clone https://github.com/your/repo.git /home/ubuntu/k8s-manifests
      cd /home/ubuntu/k8s-manifests

      # Install K3s (using the latest stable version)
      curl -sfL https://get.k3s.io | sh -

      # Ensure K3s is installed
      systemctl enable k3s
      systemctl start k3s

      # Wait for K3s to start
      sleep 30

      # Apply manifests stored in the repo
      kubectl apply -f /home/ubuntu/k8s-manifests/

      # Ensure the K3s service is enabled on boot
      systemctl enable k3s

runcmd:
  # Run the script during boot to start the K3s installation and apply the manifests
  - [ bash, /etc/init.d/bootstrap_k3s.sh ]