apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: actual-budget
  namespace: kube-system
spec:
  repo: https://charts.actualbudget.com
  chart: actual-budget
  targetNamespace: argocd
  version: 1.0.0
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/actual-budget/values.yaml'