apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo/argo-cd
    targetRevision: 7.8.23
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd