apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: open-project
  namespace: kube-system
spec:
  repo: https://charts.openproject.org
  chart: open-project
  targetNamespace: argocd
  version: 12.1.0
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/open-project/values.yaml'
