apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: redis
  targetNamespace: argocd
  version: 20.11.3
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/redis/values.yaml'