apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
    traefik.ingress.kubernetes.io/router.rule: "Host(`argocd.promotesudbury.ca`)"
spec:
  ingressClassName: traefik  # Use this instead of the deprecated annotation
  rules:
  - host: argocd.promotesudbury.ca  # Replace with your domain or external IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80