apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mcconnellj/k3s-server.git
        revision: HEAD
        files:
          - path: 'applications/**-config.yaml'
  template:
    metadata:
      name: '{{ .metadata.name }}'
    spec:
      project: default
      source:
        repoURL: '{{ .spec.source.repoURL }}'
        targetRevision: '{{ .spec.source.targetRevision }}'
        path: '{{ .spec.source.chart }}'
        helm:
          releaseName: '{{ .metadata.name }}'
          valueFiles:
            - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/HEAD/applications/{{ .metadata.name }}/values.yaml'
            - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/HEAD/applications/{{ .metadata.namespace }}-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .spec.destination.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2

#keep 
# valueFiles:
#   - "https://raw.githubusercontent.com/mcconnellj/k3s-server/HEAD/applications/{{ .appName }}/values.yaml"
#   - "https://raw.githubusercontent.com/mcconnellj/k3s-server/HEAD/applications/{{ .appEnvironment }}-values.yaml"
