apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-deployment
  namespace: argocd
spec:
  generators:
    - clusters: {}
    - git:
        repoURL: https://github.com/mcconnellj/k3s-server.git
        revision: HEAD
        files:
          - path: applications/*/*-config.yaml
  template:
    metadata:
      name: "{{ .cluster }}-{{ .app-name }}"
    spec:
      project: default
      source:
        repoURL: "{{ .app-repoUrl }}"
        targetRevision: "{{ .app-version }}"
        path: "{{ .app-chart }}"
        helm:
          releaseName: "{{ .app-name }}"
          valueFiles:
            - "https://raw.githubusercontent.com/mcconnellj/k3s-server/HEAD/applications/{{ .appName }}/values.yaml"
            - "https://raw.githubusercontent.com/mcconnellj/k3s-server/HEAD/applications/{{ .appEnvironment }}-values.yaml"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2