apiVersion: argoproj.io/v1alpha1
kind: AppNamespace
metadata:
  name: core
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: core