apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data
  namespace: argocd
  labels:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Data storage and services (databases, caches)
  sourceRepos:
    - https://git.example.com/data/*
  destinations:
    - namespace: data
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: 'external-secrets.io'
      kind: 'ClusterSecretStore'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin for data project
      policies:
        - p, proj:data:admin, applications, *, data/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
  labels:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Core platform services (auth, secrets, logging)
  sourceRepos:
    - https://git.example.com/core/*
  destinations:
    - namespace: core
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: 'external-secrets.io'
      kind: 'ClusterSecretStore'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin for core project
      policies:
        - p, proj:core:admin, applications, *, core/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edge
  namespace: argocd
  labels:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Ingress, proxies (e.g., Cilium), and routing components
  sourceRepos:
    - https://git.example.com/edge/*
  destinations:
    - namespace: edge
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: 'cilium.io'
      kind: 'CiliumNetworkPolicy'
    - group: 'gateway.networking.k8s.io'
      kind: 'Gateway'
    - group: 'external-secrets.io'
      kind: 'ClusterSecretStore'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin for edge project
      policies:
        - p, proj:edge:admin, applications, *, edge/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-alpha
  namespace: argocd
  labels:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Isolated tenant environment for Alpha client
  sourceRepos:
    - https://git.example.com/tenants/alpha
  destinations:
    - namespace: tenant-alpha
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: tenant-admin
      description: Admin for tenant-alpha project
      policies:
        - p, proj:tenant-alpha:tenant-admin, applications, *, tenant-alpha/*, allow
