apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  createNamespace: true
  version: 7.8.18
  valuesFiles:
    - https://github.com/mcconnellj/k3s-server/applications/argocd/default.values.yaml
    - https://github.com/mcconnellj/k3s-server/applications/argocd/development.values.yaml