apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  version: 7.8.18
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mcconnellj/k3s-server
        revision: HEAD
        files:
          - path: configs/kubernetes/namespace.yaml
  template:
    metadata:
      name: 'namespace-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/mcconnellj/k3s-server
        targetRevision: HEAD
        path: templates/namespace
        helm:
          parameters:
            - name: parameters
              value: '{{ . | toJson }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true