apiVersion: v1
kind: Secret
metadata:
  name: mcconnellj-k3s-server
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
stringData:
  type: git
  name: mcconnellj-k3s-server
  url: https://github.com/mcconnellj/k3s-server.git