apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    environment: development
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd  # ArgoCD projects belong in the argocd namespace
spec:
  description: "Project for development applications"
  sourceRepos:
    - "*"  # Allow all repositories (adjust as needed)
  destinations:
    - namespace: development
      server: https://kubernetes.default.svc  # Targets the local K3s cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true  # Warn about orphaned resources