apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/server-manifests/traefik/values.yaml.skip'