apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-development
  namespace: data
spec:
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: hashicorp/vault
    targetRevision: 0.30.0
  destination:
    server: https://kubernetes.default.svc
    namespace: data