apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki
  targetNamespace: argocd
  version: 2.5.0
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/loki/values.yaml'
