apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: kube-system
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  targetNamespace: vault
  version: 0.29.1
  valuesFile: 'https://raw.githubusercontent.com/hashicorp/vault-helm/main/docs/values.yaml'
