apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: edge  # You can change this if you want a different namespace
spec:
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.25.1
  destination:
    server: https://kubernetes.default.svc
    namespace: edge
  helm:
    valueFiles:
      - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/development/applications/istiod/values.yaml'
      - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/development/applications/istiod/development.yaml'