apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: enhanced-k3s-cluster
spec:
  cloudCredentialSecretName: cattle-global-data:cc-fllv6
  kubernetesVersion: v1.26.7+k3s1
  defaultPodSecurityAdmissionConfigurationTemplateName: restricted
  localClusterAuthEndpoint:
    enabled: true
  rkeConfig:
    additionalManifest: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: extra-namespace
    chartValues:
      traefik:
        additionalArguments:
          - "--log.level=DEBUG"
      metrics-server:
        args:
          - --kubelet-insecure-tls
    machineGlobalConfig:
      disable-apiserver: false
      disable-cloud-controller: false
      disable-controller-manager: false
      disable-etcd: false
      disable-kube-proxy: false
      disable-network-policy: false
      disable-scheduler: false
      etcd-expose-metrics: true
      secrets-encryption: true
      kube-apiserver-arg:
        - audit-policy-file=/etc/rancher/k3s/user-audit-policy.yaml
        - audit-log-path=/etc/rancher/k3s/user-audit.logs
      tls-san:
        - "api.example.com"
      flannel-conf: |
        Network: 10.42.0.0/16
      private-registry: |
        mirrors:
          docker.io:
            endpoint:
              - "http://mycustomreg.com:5000"
        configs:
          "mycustomreg.com:5000":
            auth:
              username: myuser
              password: mypass
    machinePools:
      - name: pool1
        quantity: 1
        controlPlaneRole: true
        etcdRole: true
        workerRole: true
        machineConfigRef:
          kind: Amazonec2Config
          name: nc-test-pool1-pwl5h
        unhealthyNodeTimeout: 5m
        drainBeforeDelete: true
        nodeLabels:
          environment: production
        taints:
          - key: "critical"
            value: "true"
            effect: "NoSchedule"
    machineSelectorConfig:
      - config:
          docker: false
          selinux: true
          protect-kernel-defaults: true
        machineLabelSelector:
          matchLabels:
            environment: production
    machineSelectorFiles:
      - fileSources:
          - secret:
              name: audit-policy
              items:
                - key: audit-policy
                  path: /etc/rancher/k3s/user-audit-policy.yaml
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: "true"
    registries: {}
    network:
      clusterCIDR: 10.42.0.0/16
      serviceCIDR: 10.43.0.0/16
      clusterDNS: 10.43.0.10
      clusterDomain: cluster.local
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      controlPlaneDrainOptions:
        enabled: true
        force: true
        ignoreDaemonSets: true
        gracePeriod: 30
        deleteEmptyDirData: true
        timeout: 120
      workerConcurrency: "2"
      workerDrainOptions:
        enabled: true
        force: false
        ignoreDaemonSets: true
        gracePeriod: 60
        deleteEmptyDirData: true
        timeout: 180