helm repo add community-charts https://community-charts.github.io/helm-charts
helm install my-actualbudget community-charts/actualbudget --version 1.4.2

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 70.4.1

helm repo add argo https://argoproj.github.io/argo-helm
helm install my-argo-cd argo/argo-cd --version 7.8.23

helm repo add traefik https://traefik.github.io/charts
helm install my-traefik traefik/traefik --version 34.5.0

helm repo add hashicorp https://helm.releases.hashicorp.com
helm install my-vault hashicorp/vault --version 0.30.0

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-keycloak bitnami/keycloak --version 24.5.0

helm repo add grafana https://grafana.github.io/helm-charts
helm install my-loki grafana/loki --version 6.29.0

helm repo add openproject-helm-charts https://charts.openproject.org
helm install my-openproject openproject-helm-charts/openproject --version 9.8.3

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-postgresql bitnami/postgresql --version 16.6.0

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-redis bitnami/redis --version 20.11.4

