write-kubeconfig-mode: "0644"
write-kubeconfig: "/etc/rancher/k3s/k3s.yaml"
cluster-name: "cloud-development"
flannel-backend: "none"
disable-kube-proxy: true
disable-network-policy: true
cluster-init: true
disable:
  - servicelb
  - traefik
node-ip: 192.168.0.47
advertise-address: 192.168.0.47
tls-san:
  - 192.168.0.47