components:
  applications:
    - name: traefik
      chart: traefik/traefik
      version: "34.4.1"
      releaseName: traefik 
      repoUrl: "https://traefik.github.io/charts"
      namespace: wave-one
      clusterName: default 
      source:
        chart: traefik
        repoURL: "https://traefik.github.io/charts"
        targetRevision: "34.4.1"