components:
  chart:
    - name: appproject-crd
      url: https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/appproject-crd.yaml
    - name: traefik-crd
      url: https://github.com/traefik/traefik-helm-chart/releases/download/v34.2.1/traefik-crds.yaml
  namespace:
    - name: edge
    - name: tenant
    - name: infra
    - name: core
  project:
    - name: development
      namespace: development
    - name: production
      namespace: production