{{- range .Values.parameters }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision | default "HEAD" }}
    path: {{ .path }}
  destination:
    server: {{ .server }}
    namespace: {{ .destinationNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
