{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
spec:
  selector:
    {{- toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: https
        protocol: {{ .Values.istio.gateway.protocol }}
      tls:
        mode: {{ .Values.istio.gateway.tls.mode }}
        credentialName: {{ .Values.istio.gateway.tls.credentialName }}
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ . }}
        {{- end }}
{{- end }}