apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: data
spec:
  source:
    repoURL: https://gissilabs.github.io/charts/
    chart: vaultwarden
    targetRevision: 1.2.5
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  helm:
    valueFiles:
      - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/development/applications/vaultwarden/values.yaml'
      - 'https://raw.githubusercontent.com/mcconnellj/k3s-server/development/applications/vaultwarden/development.yaml'