apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-development
  namespace: data
spec:
  source:
    repoURL: https://gissilabs.github.io/charts/
    chart: vaultwarden
    targetRevision: 1.2.5
  destination:
    server: https://kubernetes.default.svc
    namespace: data