apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault-warden
  namespace: kube-system
spec:
  repo: https://charts.nikiv.dev
  chart: vault-warden
  targetNamespace: argocd
  version: 1.0.0
  valuesFile: 'https://raw.githubusercontent.com/mcconnellj/k3s-server/manifests/vault-warden/values.yaml'
